# AIDI-1100 - AI Development
### Lab Activity 2 (10% of the final grade)

# Question 1:

 **a)** Write a code segment to create and print a two-dimentional 5x4 array (i.e. grid). The elements of the grid should be randomly selected from the inclusive interval [-50, 50]. Set the seed to 1 to reproduce the results. **2 Points**


In [1]:
import numpy as np
import random
np.random.seed(1) 
nd = np.random.randint(-50,50, size =(5,4))
print(nd)

[[-13 -38  22 -41]
 [ 25 -45  29  14]
 [-34 -49  26  21]
 [-44 -25   0 -30]
 [-32  34 -39 -22]]


**b)** Write a code segment that searches the `ndarray` object in `Q1a` for all the negative integers, and prints them. **3 Points**

In [2]:
for i in nd:
    print(i[i<0])

[-13 -38 -41]
[-45]
[-34 -49]
[-44 -25 -30]
[-32 -39 -22]


**c)** Given that `iList = [1, -1, 2, -2]`, add each element of `iList` to its corresponding element of `Q1a` `ndarray` row-wise.  

For example, if the Grid is equal to: $$\begin{pmatrix} 1 & 2 & 1 & 1 \\ 3 & 0 & 1 & 6 \\ 0 & 2 & 4 & 6 \\ 4 & 5 &0 & 2 \\ 3 & 6 & 4 & 3 \end{pmatrix}$$

Then the output should be:
$$\begin{pmatrix} 1+1 & 2-1 & 1+2 & 1-2 \\ 3+1 & 0-1 & 1+2 & 6-2 \\ 0+1 & 2-1 & 4+2 & 6-2 \\ 4+1 & 5-1 &0+2 & 2-2 \\ 3+1 & 6-1 & 4+2 & 3-2 \end{pmatrix}$$

In [3]:
iList = [1, -1, 2, -2]
print(nd + iList)

[[-12 -39  24 -43]
 [ 26 -46  31  12]
 [-33 -50  28  19]
 [-43 -26   2 -32]
 [-31  33 -37 -24]]


# Question 2:
According to the documentation of each method, complete the code of the `TextProcessor` class and its subclass `TextAnalyzer`. **5 Points**

In [4]:
class TextProcessor:
    def __init__(self, text):
        self.text = text
    def setStopWords(self, stop_words=[]):
        self.__stop_words = stop_words
    def getStopWords(self):
        return self.__stop_words
    def getUniqWords(self):
        return set(self.__text.split())
    def getFilteredText(self):
        word = self.text.split()
        filt = self.text
        for i in word:
            if i in self.__stop_words:
                filt = filt.replace(i + ' ','')
        return filt
class TextAnalyzer(TextProcessor):
    def __init__(self,text):
        super().__init__(text)
    def getWordFrequency(self):
        word = super().getFilteredText()
        wordFreq = {}
        for word in word.split():
            if word in wordFreq.keys():
                wordFreq[word] = wordFreq[word] + 1
            else:
                wordFreq[word] = 1
        return wordFreq
    

In [5]:
### Example test
ta = TextAnalyzer("a quick brown fox " + 
                  "a quick brown fox jumps " + 
                  "a quick brown fox jumps over " + 
                  "a quick brown fox jumps over the " + 
                  "a quick brown fox jumps over the lazy " + 
                  "a quick brown fox jumps over the lazy dog")
ta.setStopWords(['a', 'the'])
ta.getWordFrequency()

{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}